import React from 'react';

class Text extends React.Component {
	render() {
		return (
			<>
			<h2>Introduction</h2>
			<p>Welcome to my CS 185 PR3!</p>
			<p>My name is Anthony Hall, and I am a fourth-year CS major. Ever since taking computer graphics (CS 180) here last year, I have found a bit of a passion for writing procedural shaders on <a href="https://www.shadertoy.com" title="Shadertoy">Shadertoy</a>.</p>
			<p>What is a shader? A shader can be thought of as a program that several pixels individually run in parallel given some inputs (e.g. position) to generate an output color. So everything you find on this site is exactly that - images generated by code (and sometimes external assets such as images).</p>
			<p>If any of that sounds exciting, be sure to navigate to the other pages to find a shader gallery, useful videos, and links to my own projects!</p>
			<p>(Note: the input fields requirements that I did not have for PR1, as well as the new JS-validated email field, are all in the Forms page.)</p>
			</>
		);
	}
}

export default Text;